/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.palmaactiva.intro_programacion.modulo2.dni_ui;

/**
 *
 * @author usuari
 */
public class VentanaDNI extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDNI
     */
    public VentanaDNI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNumeroDNI = new javax.swing.JTextPane();
        labelError = new javax.swing.JLabel();
        buttonCalcularLetraDNI = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelLetraDNI = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cálculo Letra DNI");
        setMinimumSize(new java.awt.Dimension(271, 300));
        setPreferredSize(new java.awt.Dimension(271, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(271, 300));

        textNumeroDNI.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        textNumeroDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNumeroDNIKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNumeroDNIKeyPressed(evt);
            }
        });

        labelError.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        labelError.setForeground(new java.awt.Color(245, 30, 30));
        labelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelError.setText("Por favor introduce un múmero válido");
        labelError.setVisible(false);

        buttonCalcularLetraDNI.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        buttonCalcularLetraDNI.setText("CALCULAR");
        buttonCalcularLetraDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcularLetraDNIActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel2.setText("Introduce tu número de DNI;:");

        labelLetraDNI.setFont(new java.awt.Font("Noto Sans", 1, 48)); // NOI18N
        labelLetraDNI.setForeground(new java.awt.Color(18, 58, 136));
        labelLetraDNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLetraDNI.setText(" ");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel4.setText("Tu letra de DNI es:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelLetraDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNumeroDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(buttonCalcularLetraDNI))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNumeroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCalcularLetraDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLetraDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalcularLetraDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcularLetraDNIActionPerformed
        String numeroDniStr = this.textNumeroDNI.getText().trim();
        try {
            int numeroDni = Integer.parseInt(numeroDniStr);
            this.labelError.setVisible(false);
            char letraDNI = com.palmaactiva.intro_programacion.modulo1.bucles.EjercicioDNIAvanzado.getLetraDNI(numeroDni);
            this.labelLetraDNI.setText(Character.toString(letraDNI));
        } catch (NumberFormatException nfe) {
            this.labelError.setVisible(true);
        }
    }//GEN-LAST:event_buttonCalcularLetraDNIActionPerformed

    private void textNumeroDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumeroDNIKeyTyped
        String numeroDniStr = this.textNumeroDNI.getText().trim();
        try {
            Integer.parseInt(numeroDniStr);
        } catch (NumberFormatException nfe) {
            String nuevoNumeroDniStr = "";
            for (char letra : numeroDniStr.toCharArray()) {
                try {
                    Integer.parseInt(Character.toString(letra));
                    nuevoNumeroDniStr += letra;
                } catch (NumberFormatException nfeLetra) {
                    // No hacer nada
                }
            }
            this.textNumeroDNI.setText(nuevoNumeroDniStr);
        }
    }//GEN-LAST:event_textNumeroDNIKeyTyped

    private void textNumeroDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumeroDNIKeyPressed
        if (evt.getKeyCode() == 10){
            this.buttonCalcularLetraDNI.doClick();
        }              
    }//GEN-LAST:event_textNumeroDNIKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDNI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDNI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDNI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDNI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDNI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalcularLetraDNI;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelLetraDNI;
    private javax.swing.JTextPane textNumeroDNI;
    // End of variables declaration//GEN-END:variables
}
